! Fichier généré automatiquement - Ne pas modifier à la main
hostname router-a
password zebra

router bgp 65001
 bgp router-id 1.1.1.1
 no bgp ebgp-requires-policy
 neighbor 172.20.0.2 remote-as 65002
 neighbor 172.20.0.2 description Peering BGP

 address-family ipv4 unicast
  network 10.10.1.0/24
  neighbor 172.20.0.2 activate
 exit-address-family

line vty
!
