! Fichier généré automatiquement - Ne pas modifier à la main
hostname router-a
password zebra

router bgp 65003
 bgp router-id 1.1.1.1
 network 10.0.1.0/24
 neighbor 172.20.0.2 remote-as 65002
 neighbor 172.20.0.2 description Peering BGP

line vty
!