! Fichier généré automatiquement - Ne pas modifier à la main
hostname router-b
password zebra

router bgp 65002
 bgp router-id 2.2.2.2
 no bgp ebgp-requires-policy
 neighbor 172.20.0.5 remote-as 65001
 neighbor 172.20.0.5 description Peering BGP

 address-family ipv4 unicast
  network 10.10.2.0/24
  neighbor 172.20.0.5 activate
 exit-address-family

line vty
!
